vim.g.mapleader = ' ' -- set the space to start a shortcut
vim.g.maplocalleader = ' ' -- same as above
vim.opt.number = true -- show line number
vim.opt.clipboard = "unnamedplus" -- used to copy yank to system clipboard
vim.opt.tabstop = 4 -- 4 spaces when tab is pressed
vim.opt.shiftwidth = 4 -- 4 spaces for auto indentation
vim.opt.cursorline = true -- cursor on normal mode
vim.opt.autoread = true -- updates if file modified outside
vim.opt.autowrite = true -- autosave
vim.opt.showcmd = true -- show commands being executed
vim.opt.winborder = 'rounded' -- style rounded for floating windows
vim.keymap.set("n", "<leader>gg", ":LazyGit<CR>", { silent = true })
